# Generated by Django 6.0.3 on 2026-03-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filarequest',
            name='authorization',
        ),
        migrations.AddField(
            model_name='filarequest',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
