services:
  postgres:
    image: postgres:16
    container_name: postgres_back
    restart: unless-stopped
    env_file:
      - .env
    # secrets:
    #   - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:7
    container_name: redis_back
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: