name: workflow backend-django

on:

  push:
    branches:
      - develop
    # paths:
    #   - 'backend/**'

  pull_request:
    branches:
      - develop
    # paths:
    #   - 'backend/**'

defaults:
  run:
    shell: bash
    working-directory: backend/core

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.0"

      - name: Instalar dependências
        run: uv sync

      - name: subindo o banco
        run: docker compose up -d

      - name: Migrar banco

        run: uv run python manage.py migrate

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.0"

      - name: Instalar dependências
        run: uv sync

      - name: Rodar testes
        run: uv run pytest tests/
